name: Notificación Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: node hola.js

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: Nueva subida al repositorio" \
               -H "Priority: high" \
               -d "¡El código fue subido exitosamente a la rama main!" \
               https://ntfy.sh/devops-itla
      - name: Enviar notificación a Alerta